//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.ControlsBasics.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.Kinect.ControlsBasics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected item #{0}.
        /// </summary>
        internal static string SelectedMessage {
            get {
                return ResourceManager.GetString("SelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;grammar version=&quot;1.0&quot; xml:lang=&quot;en-US&quot; mode=&quot;voice&quot; root=&quot;destination&quot;
        ///xmlns=&quot;http://www.w3.org/2001/06/grammar&quot; tag-format=&quot;semantics/1.0&quot;&gt;
        ///
        ///  &lt;rule id=&quot;select&quot;&gt;
        ///    Open
        ///    &lt;one-of&gt;
        ///      &lt;item&gt;
        ///        one &lt;tag&gt; out=1; &lt;/tag&gt;
        ///      &lt;/item&gt;
        ///      &lt;item&gt;
        ///        two &lt;tag&gt; out=2; &lt;/tag&gt;
        ///      &lt;/item&gt;
        ///      &lt;item&gt;
        ///        three &lt;tag&gt; out=3; &lt;/tag&gt;
        ///      &lt;/item&gt;
        ///      &lt;item&gt;
        ///        four &lt;tag&gt; out=4; &lt;/tag&gt;
        ///      &lt;/item&gt;
        ///      &lt;item&gt;
        ///        five &lt;tag&gt; out=5; &lt;/tag&gt;
        ///      &lt;/item&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WindowGrammar {
            get {
                return ResourceManager.GetString("WindowGrammar", resourceCulture);
            }
        }
    }
}
