//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinectPowerPointControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinectPowerPointControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;grammar version=&quot;1.0&quot; xml:lang=&quot;en-US&quot; mode=&quot;voice&quot; root= &quot;Expression&quot;
        ///xmlns=&quot;http://www.w3.org/2001/06/grammar&quot; tag-format=&quot;semantics/1.0&quot;&gt;
        ///
        ///  &lt;rule id=&quot;Expression&quot; scope=&quot;public&quot;&gt;
        ///    &lt;example&gt;open file seven&lt;/example&gt;
        ///    &lt;tag&gt;out.number=0;&lt;/tag&gt;
        ///    &lt;one-of&gt;
        ///      &lt;item&gt;
        ///        &lt;item repeat=&quot;1&quot;&gt;open file&lt;/item&gt;
        ///        &lt;ruleref uri =&quot;#Number&quot; type=&quot;application/srgs+xml&quot;/&gt;
        ///        &lt;tag&gt;out.number=rules.latest();&lt;/tag&gt;
        ///      &lt;/item&gt;
        ///    &lt;/one-of&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string image_presentation {
            get {
                return ResourceManager.GetString("image_presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;grammar version=&quot;1.0&quot; xml:lang=&quot;en-US&quot; mode=&quot;voice&quot; root= &quot;Expression&quot;
        ///xmlns=&quot;http://www.w3.org/2001/06/grammar&quot; tag-format=&quot;semantics/1.0&quot;&gt;
        ///
        ///  &lt;rule id=&quot;Expression&quot; scope=&quot;public&quot;&gt;
        ///    &lt;example&gt;open file seven&lt;/example&gt;
        ///    &lt;tag&gt;out.number=0;&lt;/tag&gt;
        ///    &lt;one-of&gt;
        ///      &lt;item&gt;
        ///        &lt;item repeat=&quot;1&quot;&gt;open file&lt;/item&gt;
        ///        &lt;ruleref uri =&quot;#Number&quot; type=&quot;application/srgs+xml&quot;/&gt;
        ///        &lt;tag&gt;out.number=rules.latest();&lt;/tag&gt;
        ///      &lt;/item&gt;
        ///    &lt;/one-of&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slide_presentation {
            get {
                return ResourceManager.GetString("slide_presentation", resourceCulture);
            }
        }
    }
}
